### ISSUE TITLE
Comsat-servlet-undertow and out of memory: direct buffer memory

### ISSUE THREAD

**Issue by zloster** [zloster/FrameworkBenchmarks#76]
https://tfb-status.techempower.com/unzip/results.2019-05-04-11-56-15-224.zip/results/20190430202646/comsat-servlet-undertow/run/comsat-servlet-undertow.log

> comsat-servlet-undertow: Exception in Fiber "fiber-13407032" java.lang.OutOfMemoryError: Direct buffer memory
comsat-servlet-undertow: java.lang.OutOfMemoryError: Direct buffer memory
comsat-servlet-undertow: java.lang.OutOfMemoryError: Direct buffer memory
comsat-servlet-undertow: java.lang.OutOfMemoryError: Direct buffer memory
comsat-servlet-undertow: Exception in Fiber "fiber-13407018" Exception in Fiber "fiber-13407028" java.lang.OutOfMemoryError: Direct buffer memory
comsat-servlet-undertow: 	at java.nio.Bits.reserveMemory(Bits.java:695)
comsat-servlet-undertow: 	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
comsat-servlet-undertow: 	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)

Tweak the JVM parameter to see if it helps. If not - probably the problem will be more serious. But Comsat is not under active development and maintenance - so most probably it will not worth fixing.

**Comment by zloster** [comment]
The change is ready. Awaiting for failing Travis fix - toolset has some problem.

**Comment by zloster** [comment]
Submitted...
