### ISSUE TITLE
Java 11 update

### ISSUE THREAD

**Issue by zloster** [zloster/FrameworkBenchmarks#80]
Let's see what is still using Java 10 and below:

Java 8:
- [x] ./Java/jooby/jooby.dockerfile
- [x] ./Java/helidon/helidon.dockerfile
- [x] ./Java/voovan/voovan.dockerfile
- [x] ./Java/t-io/tio-mvc.dockerfile
- [x] ./Java/jooby2/jooby2-jetty.dockerfile
- [x] ./Java/jooby2/jooby2.dockerfile
- [x] ./Java/jooby2/jooby2-undertow.dockerfile
- [x] ./Java/blade/blade.dockerfile
- [x] ./Java/smart-socket/smart-socket.dockerfile
- [ ] ./Java/act/act-eclipselink-mysql-rythm.dockerfile
- [ ] ./Java/act/act-ebean-mysql-rythm.dockerfile
- [ ] ./Java/act/act-hibernate-pgsql.dockerfile
- [ ] ./Java/act/act-morphia-mongo.dockerfile
- [ ] ./Java/act/act-ebean-pgsql-rythm.dockerfile
- [ ] ./Java/act/act.dockerfile
- [ ] ./Java/act/act-hibernate-mysql-rythm.dockerfile
- [ ] ./Java/act/act-eclipselink-pgsql-rythm.dockerfile
- [ ] ./Java/act/act-ebean-mysql.dockerfile
- [ ] ./Java/act/act-hibernate-mysql.dockerfile
- [ ] ./Java/act/act-eclipselink-pgsql.dockerfile
- [ ] ./Java/act/act-hibernate-pgsql-rythm.dockerfile
- [ ] ./Java/act/act-eclipselink-mysql.dockerfile
- [ ] ./Java/act/act-morphia-mongo-rythm.dockerfile
- [ ] ./Java/act/act-ebean-pgsql.dockerfile

Another portion:
```$  find . -name "*.dockerfile" -exec grep -l "jdk8" {} \;```
 - [x] jawn
 - [ ] comsat
 - [x] ratpack
 - [x] javalin
 - [x] wizzardo-http

YAP (yet another portion):
 - [x] Kotlin/http4k
 - [x] Kotlin/ktor
 - [ ] ./Kotlin/pronghorn
 - [x] ./Kotlin/hexagon

JavaScript/ringojs and Groovy/hot not possible for update.

From Java 10:
 - [x] Java/armeria/armeria.dockerfile
 - [x]   Java/baratine/baratine.dockerfile
 - [x]   Java/bayou/bayou.dockerfile
 - [x]   Java/firenio/firenio-http-lite.dockerfile
 - [x] Java/firenio/firenio.dockerfile
 - [x] Java/httpserver/httpserver-postgres.dockerfile
 - [x] Java/httpserver/httpserver.dockerfile
 - [x] Java/jlhttp/jlhttp-postgres.dockerfile
 - [x] Java/jlhttp/jlhttp.dockerfile
 - [x] Java/minijax/minijax.dockerfile
 - [x] Java/nanohttpd/nanohttpd.dockerfile
 - [x] Java/netty/netty.dockerfile
 - [x] Java/proteus/proteus-mysql.dockerfile
 - [x] Java/proteus/proteus.dockerfile
 - [x] Java/rapidoid/rapidoid-http-fast.dockerfile
 - [x] Java/rapidoid/rapidoid-mysql.dockerfile
 - [x] Java/rapidoid/rapidoid-postgres.dockerfile
 - [x] Java/rapidoid/rapidoid.dockerfile
 - [x] Java/redkale/redkale-postgres.dockerfile
 - [x] Java/redkale/redkale.dockerfile
 - [x] Java/restexpress/restexpress-mysql-raw.dockerfile
 - [x] Java/restexpress/restexpress.dockerfile
 - [x] Java/servlet3/servlet3-sync.dockerfile
 - [x] Java/servlet3/servlet3.dockerfile
 - [x] Java/vertx-web/vertx-web-mongodb.dockerfile
 - [x] Java/vertx-web/vertx-web-postgres.dockerfile
 - [x] Java/vertx-web/vertx-web-susom-postgres.dockerfile
 - [x] Java/vertx-web/vertx-web.dockerfile
 - [x] Java/vertx/vertx-postgres.dockerfile
 - [x] Java/vertx/vertx.dockerfile

**Comment by zloster** [comment]
~~smartsocket has strange dependencies.~~
Actually just Maven coordinates change.
Edit: smartsocket was just updated with the latest dependencies. Now check if update to Java 11 is possible.
Edit 2: but after it is merged.

**Comment by zloster** [comment]
Blade has a problem with Java 11 in `fortunes`.
Edit: It needed explicit transitive dependency update for the views.

**Comment by zloster** [comment]
Jooby2 needs dependencies updates - refuses to start. The exceptions request `AST7` to be used.
Edit: But the `pom` is **inheriting**  their parent `pom`. So a little tricky...
Edit 2: Not so tricky at the end. The `pom` inheritance was creating the problme - I've only replaced the Jooby version in `properties` but not in the parent `pom` section.

**Comment by zloster** [comment]
`act` is failing also:
```
act: WARNING: An illegal reflective access operation has occurred
act: WARNING: Illegal reflective access by org.osgl.util.Unsafe (file:/root/.m2/repository/org/osgl/osgl-tool/1.19.2/osgl-tool-1.19.2.jar) to field java.lang.String.value
act: WARNING: Please consider reporting this to the maintainers of org.osgl.util.Unsafe
act: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
act: WARNING: All illegal access operations will be denied in a future release
act: Exception in thread "main" java.lang.ExceptionInInitializerError
act: 	at org.osgl.util.FastStr.toString(FastStr.java:584)
act: 	at org.osgl.util.FastStr.toLowerCase(FastStr.java:1276)
act: 	at org.osgl.util.FastStr.toLowerCase(FastStr.java:47)
act: 	at org.osgl.util.StrBase.toLowerCase(StrBase.java:1551)
act: 	at org.osgl.util.Keyword.init(Keyword.java:509)
act: 	at org.osgl.util.Keyword.<init>(Keyword.java:243)
act: 	at org.osgl.util.Keyword.of(Keyword.java:442)
act: 	at act.conf.Config.canonical(Config.java:214)
act: 	at act.conf.AppConfigKey.<init>(AppConfigKey.java:1324)
act: 	at act.conf.AppConfigKey.<init>(AppConfigKey.java:1320)
act: 	at act.conf.AppConfigKey.<clinit>(AppConfigKey.java:61)
act: 	at act.Act.bootstrap(Act.java:1161)
act: 	at act.Act.start(Act.java:676)
act: 	at com.techempower.act.AppEntry.main(AppEntry.java:31)
act: Caused by: org.osgl.exception.UnexpectedException: java.lang.NoSuchMethodException: java.lang.String.<init>([C, boolean)
act: 	at org.osgl.util.E.unexpected(E.java:189)
act: 	at org.osgl.util.Unsafe.<clinit>(Unsafe.java:50)
act: 	... 14 more
act: Caused by: java.lang.NoSuchMethodException: java.lang.String.<init>([C, boolean)
act: 	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
act: 	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
act: 	at org.osgl.util.Unsafe.<clinit>(Unsafe.java:44)
act: 	... 14 more
act: sub process returned with exit code: 1
act: [ERROR] Failed to execute goal org.actframework:act-maven-plugin:1.8.12.0:test (default) on project actframework: End to end test failed -> [Help 1]
```

**Comment by zloster** [comment]
Act can't be updated currently due to the dependency to: https://github.com/osglworks/java-tool/issues/198

**Comment by zloster** [comment]
Act can't be updated currently due to the dependency to: osglworks/ java-tool/ {} issues/198

**Comment by zloster** [comment]
The only left is `smart-socket`. Probably today they will merge the updates.

**Comment by zloster** [comment]
The PR about most of the frameworks is merged.

**Comment by zloster** [comment]
My branch with updated Java for smart-socket is building.

**Comment by zloster** [comment]
`javalin` is ready.

**Comment by zloster** [comment]
`jawn` also ready.

**Comment by zloster** [comment]
`comsat-webactors-netty` and `comsat-webactors-undertow` have problem with Java 11. There is a change about `URLClassLoader` and the implementations in the library is throwing `ClassCastException`.
```
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
```

**Comment by zloster** [comment]
`wizzardo-http` is ready.

**Comment by zloster** [comment]
Pull request for `jawn`, `javalin`, `wizzardo-http` and `ratpack` is submitted.

**Comment by zloster** [comment]
`Kotlin/hexagon` was updated as part of the `resin` update.
Edit: Now `gradle` was updated also.

**Comment by zloster** [comment]
Pull request for `hexagon`, `http4k` and `ktor` is submitted.

**Comment by zloster** [comment]
`JavaScript/ringojs` and `Groovy/hot` not possible for update.

**Comment by zloster** [comment]
`baratine` is ready, `armeria` is not.

**Comment by zloster** [comment]
`armeria` is also ready.

**Comment by zloster** [comment]
`minijax` and `proteus` are ready.

**Comment by zloster** [comment]
Summary:
 - `Java/act`, `Java/comsat`, `Kotlin/pronghorn` and one of the `Java/officefloor` variants are **not** updated.
Move them for other times in a new ticket.
